# Generated by Django 5.2.8 on 2026-01-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=20, unique=True)),
                ('address', models.TextField(help_text='Store address')),
                ('phone_1', models.CharField(help_text='Primary phone number', max_length=20)),
                ('phone_2', models.CharField(blank=True, help_text='Secondary phone number (optional)', max_length=20)),
                ('email_1', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('email_2', models.EmailField(blank=True, help_text='Secondary contact email (optional)', max_length=254)),
                ('working_hours', models.TextField(help_text="Working hours text (e.g., 'Mon - Sat: 9:00 AM - 7:00 PM')")),
                ('map_embed_url', models.TextField(blank=True, help_text='Google Maps Embed URL (iframe src)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
